<?php

namespace Talon\ApiBundle\Repository;

/**
 * UrlDownloadRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlDownloadRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
